version: 3

tasks:

  build:
    cmd:
      docker build -t davinkevin/kodi-s3-source .

  push:
    cmd: |-
      docker tag davinkevin/kodi-s3-source:latest davinkevin/kodi-s3-source:$(date +"%Y.%m.%d") 
      docker push davinkevin/kodi-s3-source:$(date +"%Y.%m.%d")

  run:
    cmd: docker run -it --rm
            -p 80:80
            --env-file local.env
            davinkevin/kodi-s3-source